version: 2

builds:
  - id: default
    main: ./cmd/main.go
    binary: crdb-ory-keto-demo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: ['tar.gz', 'zip']
    name_template: "crdb-ory-keto-demo_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config/**
      - keto/**
      - scripts/**
      - docker-compose.yml

checksum:
  name_template: "checksums.txt"
